### ISSUE TITLE
updateEntityAttributes leads to an error

### ISSUE THREAD

**Issue by GekoCH** [unfoldedcircle/feature-and-bug-tracker#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I use the minimum-required.js to control my media player.
However when I try to update an Entity Attribut I get an error.

Here is the code to update the entity:
`uc.configuredEntities.updateEntityAttributes(
  "my_evita",
  new Map([[uc.Entities.MediaPlayer.ATTRIBUTES.VOLUME, 24]])
);`

ERROR:
```
/root/integration-node-library/lib/entities/entities.js:102
      this.#storage[id].attributes[key] = value;
                                        

TypeError: Cannot set properties of null (setting 'volume')
    at /root/integration-node-library/lib/entities/entities.js:102:41
    at Map.forEach (<anonymous>)
    at Entities.updateEntityAttributes (/root/integration-node-library/lib/entities/entities.js:101:16)
    at IntegrationAPI.<anonymous> (/root/integration-node-library/examples/mediaplayer/player.js:421:24)
    at IntegrationAPI.emit (node:events:514:28)
    at #entityCommand (/root/integration-node-library/index.js:476:10)
    at #messageReceived (/root/integration-node-library/index.js:353:36)

```

I used this example. uc.on events do work great but changing the Attributes of the entity fails...
https://github.com/unfoldedcircle/integration-node-library/blob/e57cd028a52775abb29d9ed81512fff9b2600c59/examples/minimum-required.js

### How to Reproduce

see above

### Expected behavior

see above

**Comment by zehnm** [comment]
Moving to https://github.com/unfoldedcircle/integration-node-library
